spring.datasource.url: jdbc:mysql://b361c88c3235d6:7533ed5a@eu-cdbr-west-03.cleardb.net/heroku_451175289957582?reconnect=true
spring.datasource.username: b361c88c3235d6
spring.datasource.password: 7533ed5a
spring.jpa.hibernate.ddl-auto: none
server.port: ${PORT:8080}

spring.liquibase.enabled: true
spring.liquibase.change-log: classpath:db.changelog\changelog-master.xml
spring.jackson.serialization-inclusion: non_null

spring.servlet.multipart.max-file-size: 128KB
spring.servlet.multipart.max-request-size: 128KB

mail.password: 74c114b8844644c661cc708121715675-29561299-4b0f8a9e
mail.url: https://api.mailgun.net/v3/sandboxcad921fc99ff4cc39294759a39a46899.mailgun.org
mail.fromMail: k.nikitaigorevich@gmail.com

blog.title: DevPub
blog.subtitle: Рассказы разработчиков
blog.phone: +7 903 666-44-55
blog.email: mail@mail.ru
blog.copyright: Дмитрий Сергеев
blog.copyrightFrom: 2005
