spring.datasource.url: jdbc:mysql://localhost:3306/blog?useUnicode=true&serverTimezone=UTC&&characterEncoding=UTF-8
spring.datasource.username: root
spring.datasource.password: root
spring.jpa.hibernate.ddl-auto: none

blog.title: DevPub
blog.subtitle: Рассказы разработчиков
blog.phone: +7 903 666-44-55
blog.email: mail@mail.ru
blog.copyright: Дмитрий Сергеев
blog.copyrightFrom: 2005